INDEPENDENTS = [
    "@SenSanders",
    "@SenAngusKing"
]

DEMOCRATS = [
    ["Virginia", "@TimKaine"],
    ["Michigan", "@StabenowPress"],
    ["Rhode Island", "@SenWhitehouse"],
    ["Massacheusetts", "@SenWarren"],
    ["Ohio", "@SenSherrodBrown"],
    ["Oregon", "@SenJeffMerkley"],
    ["Rhode Island", "@SenJackReed"],
    ["New York", "@SenGillibrand"],
    ["Michigan", "@SenGaryPeters"],
    ["California", "@SenFeinstein"],
    ["Indiana", "@SenDonnelly"],
    ["Hawaii", "@SenBrianSchatz"],
    ["Pennsylvania", "@SenBobCasey"],
    ["Connecticut", "@SenBlumenthal"],
    ["Florida", "@SenBillNelson"],
    ["Colorado", "@SenBennetCO"],
    ["New Mexico", "@SenatorTomUdall"],
    ["New Hampshire", "@SenatorShaheen"],
    ["Nevada", "@SenatorReid"],
    ["New Jersey", "@SenatorMenendez"],
    ["Vermont", "@SenatorLeahy"],
    ["North Dakota", "@SenatorHeitkamp"],
    ["Illinois", "@SenatorDurbin"],
    ["Deleware", "@SenatorCarper"],
    ["Maryland", "@SenatorCardin"],
    ["Washington", "@SenatorCantwell"],
    ["Maryland", "@SenatorBarb"],
    ["Wisconsin   SenatorBaldwin", "@"],
    ["West Virginia", "@Sen_JoeManchin"],
    ["Oregon", "@RonWyden"],
    ["Washington", "@PattyMurray"],
    ["Missouri", "@McCaskillOffice"],
    ["Hawaii", "@maziehirono"],
    ["New Mexico", "@MartinHeinrich"],
    ["Virginia", "@MarkWarner"],
    ["Massacheusetts", "@MarkeyMemo"],
    ["California", "@KamalaHarris"],
    ["Montana", "@JonTester"],
    ["New Jersey", "@CoryBooker"],
    ["New York", "@ChuckSchumer"],
    ["Connecticut", "@ChrisMurphyCT"],
    ["Minnesota", "@AmyKlobuchar"],
    ["Minnesota", "@AlFranken"],
    ["Deleware", "@ChrisCoons"]
]

REPUBLICANS = [
    "@TomCoburn",
    "@ThomTillis",
    "@SenThomTillis",
    "@SteveDaines",
    "@SenToomey",
    "@SenTomCotton",
    "@SenThadCochran",
    "@SenTedCruz ",
    "@TedCruz",
    "@SenShelby",
    "@SenRonJohnson",
    "@SenRandPaul",
    "@SenPatRoberts",
    "@SenOrrinHatch",
    "@OrrinHatch",
    "@SenMikeLee",
    "@SenJoniErnst",
    "@JoniErnst",
    "@SenJohnThune",
    "@SenJohnMcCain",
    "@SenJohnHoeven",
    "@SenJohnBarrasso",
    "@SenIsakson",
    "@SenDeanHeller",
    "@sendavidperdue",
    "@SenDanSullivan",
    "@SenDanCoats",
    "@SenCoryGardner",
    "@SenCapito",
    "@SenBobCorker",
    "@SenatorWicker",
    "@SenatorTimScott",
    "@SenatorSessions",
    "@SenatorRounds",
    "@SenatorRisch",
    "@SenatorLankford",
    "@SenatorKirk",
    "@SenatorFischer",
    "@SenatorEnzi",
    "@SenatorCollins",
    "@SenatorBurr",
    "@SenAlexander",
    "@RoyBlunt",
    "@RobPortman",
    "@MikeCrapo",
    "@McConnellPress",
    "@MarcoRubio",
    "@LisaMurkowski",
    "@KellyAyotte",
    "@JohnCornyn",
    "@JohnBoozman",
    "@JerryMoran",
    "@JeffFlake",
    "@GrahamBlog",
    "@DavidVitter",
    "@ChuckGrassley",
    "@BillCassidy",
    "@BenSasse",
    "@SenSasse"
]
